import { RiskCard, MitigationCard } from "../game.types";

export const MOCK_RISK_CARDS: RiskCard[] = [
  { id: "r1", categoryId: "task", descriptionId: "risk_1" },
  { id: "r2", categoryId: "task", descriptionId: "risk_2" },
  { id: "r3", categoryId: "task", descriptionId: "risk_3" },
  { id: "r4", categoryId: "structure", descriptionId: "risk_4" },
  { id: "r5", categoryId: "structure", descriptionId: "risk_5" },
  { id: "r6", categoryId: "structure", descriptionId: "risk_6" },
  { id: "r7", categoryId: "actor", descriptionId: "risk_7" },
  { id: "r8", categoryId: "actor", descriptionId: "risk_8" },
  { id: "r9", categoryId: "actor", descriptionId: "risk_9" },
  { id: "r10", categoryId: "technology", descriptionId: "risk_10" },
  { id: "r11", categoryId: "technology", descriptionId: "risk_11" },
  { id: "r12", categoryId: "technology", descriptionId: "risk_12" },
  { id: "r13", categoryId: "task_actor", descriptionId: "risk_13" },
  { id: "r14", categoryId: "task_actor", descriptionId: "risk_14" },
  { id: "r15", categoryId: "task_actor", descriptionId: "risk_15" },
  { id: "r16", categoryId: "task_technology", descriptionId: "risk_16" },
  { id: "r17", categoryId: "task_technology", descriptionId: "risk_17" },
  { id: "r18", categoryId: "task_technology", descriptionId: "risk_18" },
  { id: "r19", categoryId: "structure_task", descriptionId: "risk_19" },
  { id: "r20", categoryId: "structure_task", descriptionId: "risk_20" },
  { id: "r21", categoryId: "actor_technology", descriptionId: "risk_21" },
  { id: "r22", categoryId: "actor_technology", descriptionId: "risk_22" },
  { id: "r23", categoryId: "actor_structure", descriptionId: "risk_23" },
  { id: "r24", categoryId: "actor_structure", descriptionId: "risk_24" },
  { id: "r25", categoryId: "structure_technology", descriptionId: "risk_25" },
  { id: "r26", categoryId: "structure_technology", descriptionId: "risk_26" },
];

export const MOCK_MITIGATION_CARDS: MitigationCard[] = [
  { id: "m1", categoryId: "task" },
  { id: "m2", categoryId: "structure" },
  { id: "m3", categoryId: "actor" },
  { id: "m4", categoryId: "technology" },
  { id: "m5", categoryId: "task_actor" },
  { id: "m6", categoryId: "task_technology" },
  { id: "m7", categoryId: "structure_task" },
  { id: "m8", categoryId: "actor_technology" },
  { id: "m9", categoryId: "actor_structure" },
  { id: "m10", categoryId: "structure_technology" },
  { id: "m11", categoryId: "task" },
  { id: "m12", categoryId: "structure" },
  { id: "m13", categoryId: "actor" },
  { id: "m14", categoryId: "technology" },
  { id: "m15", categoryId: "task_actor" },
  { id: "m16", categoryId: "task_technology" },
  { id: "m17", categoryId: "structure_task" },
];
